Repository boostcampwm2023/and06-nibobnebob, pull requests merged in 2023-11, with the labels that each got.

#9 [etc/aos] 프로젝트 세팅
  .idea/.gitignore
  .idea/and06-nibobnebob.iml
  .idea/modules.xml
  .idea/vcs.xml
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/app/App.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ApiModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/AccessTokenInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
  Aos/app/src/main/res/layout/activity_main.xml
  Aos/app/src/main/res/values/colors.xml
Labels: AOS, chore

#11 [etc/be] 백엔드 초기세팅 #8
  be/.eslintrc.js
  be/.gitignore
  be/.prettierrc
  be/README.md
  be/nest-cli.json
  be/package-lock.json
  be/package.json
  be/src/app.controller.spec.ts
  be/src/app.controller.ts
  be/src/app.module.ts
  be/src/app.service.ts
  be/src/main.ts
  be/test/app.e2e-spec.ts
  be/test/jest-e2e.json
  be/tsconfig.build.json
  be/tsconfig.json
Labels: BE, chore

#13 백엔드 초기 세팅 완료
  be/.eslintrc.js
  be/.gitignore
  be/.prettierrc
  be/README.md
  be/nest-cli.json
  be/package-lock.json
  be/package.json
  be/src/app.controller.spec.ts
  be/src/app.controller.ts
  be/src/app.module.ts
  be/src/app.service.ts
  be/src/main.ts
  be/test/app.e2e-spec.ts
  be/test/jest-e2e.json
  be/tsconfig.build.json
  be/tsconfig.json
Labels: BE

#14 [Login/aos] 인트로 협업 준비 #6
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
Labels: feat, AOS

#27 [Register/aos] 상세 회원가입 API 제외 구현 완료
  Aos/.idea/misc.xml
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/DatePicker.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Validation.kt
  Aos/app/src/main/res/color/selector_next_btn_text.xml
  Aos/app/src/main/res/color/selector_nick_check_text.xml
  Aos/app/src/main/res/drawable/ic_back.xml
  Aos/app/src/main/res/drawable/ic_calendar.xml
  Aos/app/src/main/res/drawable/rect_dark1fill_nostroke_8radius.xml
  Aos/app/src/main/res/drawable/rect_primarylight3fill_nostroke_8radius.xml
  Aos/app/src/main/res/drawable/selector_next_btn.xml
  Aos/app/src/main/res/layout/activity_intro.xml
  Aos/app/src/main/res/layout/fragment_detail_signup.xml
  Aos/app/src/main/res/layout/fragment_login.xml
  Aos/app/src/main/res/navigation/intro_nav_graph.xml
  Aos/app/src/main/res/values-night/themes.xml
  Aos/app/src/main/res/values/colors.xml
  Aos/app/src/main/res/values/strings.xml
  Aos/app/src/main/res/values/text_style.xml
Labels: feat, AOS

#25 [MyPage/aos] Global 화면전환 설정, MyPage 메인 레이아웃 구현 #18 #20
  Aos/.idea/misc.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/FollowFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/WishRestaurantListFragment.kt
  Aos/app/src/main/res/drawable/ic_back.xml
  Aos/app/src/main/res/drawable/ic_following.xml
  Aos/app/src/main/res/drawable/ic_home.xml
  Aos/app/src/main/res/drawable/ic_mypage.xml
  Aos/app/src/main/res/drawable/menu_selector_style.xml
  Aos/app/src/main/res/layout/activity_main.xml
  Aos/app/src/main/res/layout/fragment_edit_profile.xml
  Aos/app/src/main/res/layout/fragment_follow.xml
  Aos/app/src/main/res/layout/fragment_home.xml
  Aos/app/src/main/res/layout/fragment_my_page.xml
  Aos/app/src/main/res/layout/fragment_my_restaurant_list.xml
  Aos/app/src/main/res/layout/fragment_wish_restaurant_list.xml
  Aos/app/src/main/res/menu/nav_bar.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
  Aos/app/src/main/res/values/colors.xml
  Aos/app/src/main/res/values/strings.xml
  Aos/app/src/main/res/values/text_style.xml
Labels: review, feat, AOS

#38 [MyPage/aos] 프로필 수정 API연동 제외 구현 (API 연동 전)
  .DS_Store
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageUiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/Validation.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/WishRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileUiEvent.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileUiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/my_list/MyRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/share/MyPageSharedUiEvent.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/share/MyPageSharedViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wish_list/WishRestaurantListFragment.kt
  Aos/app/src/main/res/drawable/rect_primarylight3fill_12radius.xml
  Aos/app/src/main/res/drawable/rect_wishlistcolorfill_12radius.xml
  Aos/app/src/main/res/layout/fragment_edit_profile.xml
  Aos/app/src/main/res/layout/fragment_my_page.xml
  Aos/app/src/main/res/layout/fragment_my_restaurant_list.xml
  Aos/app/src/main/res/layout/fragment_wish_restaurant_list.xml
  Aos/app/src/main/res/layout/item_my_list.xml
  Aos/app/src/main/res/layout/item_wish_list.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
  Aos/app/src/main/res/values/colors.xml
  Aos/app/src/main/res/values/strings.xml
  Aos/app/src/main/res/values/text_style.xml
Labels: feat, refactor, AOS

#37 [signup/be] 회원가입 및 DB 연동
  be/.gitignore
  be/package-lock.json
  be/package.json
  be/src/app.controller.spec.ts
  be/src/app.controller.ts
  be/src/app.module.ts
  be/src/app.service.ts
  be/src/main.ts
  be/src/user/dto/userInfo.dto.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.controller.spec.ts
  be/src/user/user.controller.ts
  be/src/user/user.module.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.spec.ts
  be/src/user/user.service.ts
Labels: feat, BE

#34 [Login/aos] 로그인 API제외 구현 완료 (API 연결 전)
  Aos/app/build.gradle.kts
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/app/App.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/DataModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/Info.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/res/drawable/ic_logo.xml
  Aos/app/src/main/res/drawable/ic_naver.xml
  Aos/app/src/main/res/drawable/rect_naverfill_nostroke_12radius.xml
  Aos/app/src/main/res/drawable/rect_primary6fill_nostroke_8radius.xml
  Aos/app/src/main/res/layout/fragment_login.xml
  Aos/app/src/main/res/values/colors.xml
  Aos/app/src/main/res/values/strings.xml
  Aos/app/src/main/res/values/text_style.xml
Labels: feat, AOS

#36 [splash/aos] 스플래시 구현
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/app/NetWorkManager.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
  Aos/app/src/main/res/drawable/ic_logo_big.xml
  Aos/app/src/main/res/layout/activity_splash.xml
  Aos/app/src/main/res/values/colors.xml
  Aos/app/src/main/res/values/strings.xml
Labels: feat, AOS

#40 백엔드 회원가입 구현
  be/.gitignore
  be/package-lock.json
  be/package.json
  be/src/app.controller.spec.ts
  be/src/app.controller.ts
  be/src/app.module.ts
  be/src/app.service.ts
  be/src/main.ts
  be/src/user/dto/userInfo.dto.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.controller.spec.ts
  be/src/user/user.controller.ts
  be/src/user/user.module.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.spec.ts
  be/src/user/user.service.ts
Labels: BE

#43 [signup/be] 회원가입 중복 value 에러 fix
  be/src/user/dto/userInfo.dto.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: fix, BE

#44 회원가입 시 중복 데이터 에러 fix
  be/src/user/dto/userInfo.dto.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#47 [signup/be] baseresponse를 위한 interceptor 구현
  be/src/baseresponse.ts
  be/src/error.filter.ts
  be/src/main.ts
  be/src/response.interceptor.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#48 baseResponse 설정
  be/src/baseresponse.ts
  be/src/error.filter.ts
  be/src/main.ts
  be/src/response.interceptor.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#49 [Home/aos] Home 네이버 맵 Setting
  Aos/app/build.gradle.kts
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivityViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
  Aos/app/src/main/res/drawable/ic_location_off.xml
  Aos/app/src/main/res/drawable/ic_location_on.xml
  Aos/app/src/main/res/layout/fragment_home.xml
  Aos/settings.gradle.kts
Labels: feat, fix, AOS

#51 [Register/be] 회원가입 상세 닉네임 중복 확인 api 구현
  be/src/app.module.ts
  be/src/baseResponse.ts
  be/src/error.filter.ts
  be/src/main.ts
  be/src/user/dto/userInfo.dto.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#54 네이버 소셜 로그인 구현
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/auth/auth.controller.spec.ts
  be/src/auth/auth.controller.ts
  be/src/auth/auth.module.ts
  be/src/auth/auth.service.spec.ts
  be/src/auth/auth.service.ts
  be/src/auth/strategy/jwt.strategy.ts
  be/src/user/user.controller.ts
  be/src/user/user.module.ts
  be/src/user/user.service.ts
Labels: BE

#55 회원가입 기능 추가
  be/src/user/dto/userInfo.dto.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#52 [Mypage/aos] 프로필 수정 완료버튼, 활동지역 Spinner로 변경
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageUiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileUiEvent.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileUiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/my_list/MyRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/share/MyPageSharedUiEvent.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/share/MyPageSharedViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wish_list/WishRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/LocationArray.kt
  Aos/app/src/main/res/drawable/ic_drop_down.xml
  Aos/app/src/main/res/drawable/selector_location_drop_down.xml
  Aos/app/src/main/res/layout/fragment_edit_profile.xml
Labels: feat, refactor, AOS

#59 마이페이지 api 처리 기능 구현
  be/src/auth/auth.module.ts
  be/src/auth/auth.service.ts
  be/src/main.ts
  be/src/user/dto/userInfo.dto.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.decorator.ts
  be/src/user/user.module.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#60 [Mypage/be] 마이 메인페이지 api 엔드포인트, 타 유저 메인페이지 api 엔드포인트 분리
  be/src/auth/strategy/jwt.strategy.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#61 마이페이지 api 추가 분리
  be/src/auth/strategy/jwt.strategy.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#74 [Login/be] refreshToken 발급
  be/src/auth/auth.module.ts
  be/src/auth/auth.service.ts
  be/src/auth/strategy/jwt.strategy.ts
  be/src/main.ts
  be/src/user/dto/userInfo.dto.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.decorator.ts
  be/src/user/user.module.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#77 [Login/be] payload 수정
  be/src/auth/auth.service.ts
Labels: fix, BE

#81 [Login/aos] 로그인 관련 api 연동(+스플래시)
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/app/App.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/DataStoreManager.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ApiModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/AccessTokenInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/ApiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/NaverLoginResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/NibobNebobApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/LoginRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/LoginRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/Info.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
  Aos/app/src/main/res/navigation/intro_nav_graph.xml
Labels: feat, AOS

#83 [Signup/aos] 회원가입 페이지 Api 연결
  Aos/.idea/deploymentTargetDropDown.xml
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/app/App.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/DataStoreManager.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ApiModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/AccessTokenInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/ApiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/DetailSignupRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/DetailSignupResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/NaverLoginResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/ValidationResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/IntroAPI.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RefreshApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/ValidationApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/ValidationRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/ValidationRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/Info.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/mapper/UiSignupDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
  Aos/app/src/main/res/layout/fragment_detail_signup.xml
  Aos/app/src/main/res/layout/fragment_login.xml
  Aos/app/src/main/res/navigation/intro_nav_graph.xml
Labels: feat, AOS

#84 [Mypage/aos] 마이페이지 메인, 프로필수정 api 연결
  Aos/.idea/deploymentTargetDropDown.xml
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/app/App.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/DataStoreManager.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ApiModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/DataModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/AccessTokenInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/ApiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/DetailSignupRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/EditMyInfoRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/DetailSignupResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyDefaultInfoResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyInfoResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/NaverLoginResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/ValidationResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/IntroApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/MyPageApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RefreshApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/ValidationApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/ValidationRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/ValidationRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository_impl/MyPageRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/Info.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/mapper/UiSignupDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyPageInfoDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMypageEditInfoMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyPageEditInfoData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyPageMainInfoData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/my_list/MyRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wish_list/WishRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/LoginType.kt
  Aos/app/src/main/res/layout/fragment_detail_signup.xml
  Aos/app/src/main/res/layout/fragment_edit_profile.xml
  Aos/app/src/main/res/layout/fragment_login.xml
  Aos/app/src/main/res/layout/fragment_my_page.xml
  Aos/app/src/main/res/layout/fragment_my_restaurant_list.xml
  Aos/app/src/main/res/layout/fragment_wish_restaurant_list.xml
  Aos/app/src/main/res/navigation/intro_nav_graph.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
  Aos/app/src/main/res/values/strings.xml
Labels: feat, AOS

#79 [Global/be] accessToken 만료 시 동작 구현
  be/src/auth/auth.controller.ts
  be/src/auth/auth.service.ts
  be/src/auth/dto/refreshToken.dto.ts
Labels: feat, BE

#82 [Signup/be] password salt 암호화 적용
  be/package-lock.json
  be/package.json
  be/src/user/entities/user.entity.ts
  be/src/user/user.service.ts
  be/src/utils/encryption.utils.ts
Labels: refactor, BE

#80 [Global/be] 모든 테이블 dto, entity 구현
  be/src/app.module.ts
  be/src/restaurant/dto/restaurantInfo.dto.ts
  be/src/restaurant/entities/restaurant.entity.ts
  be/src/restaurant/restaurant.module.ts
  be/src/review/dto/reviewInfo.dto.ts
  be/src/review/entities/review.entity.ts
  be/src/review/review.module.ts
  be/src/user/entities/user.followList.entity.ts
  be/src/user/entities/user.restaurantlist.entity.ts
Labels: feat, BE

#89 [Global/be] 로깅 및 단위 테스트 구현
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/auth/auth.module.ts
  be/src/auth/auth.service.ts
  be/src/auth/strategy/jwt.strategy.ts
  be/src/custom.logger.ts
  be/src/logger.interceptor.ts
  be/src/user/user.module.ts
  be/src/user/user.service.spec.ts
Labels: feat, test, BE

#92 [Global/be] package파일 Conflict fix
  be/package-lock.json
  be/package.json
  be/src/user/user.service.ts
Labels: fix, BE

#94 [Pair/aos] 홈 화면이동 구성, BottomSheet 구현
  Aos/.idea/deploymentTargetDropDown.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/restaurant_add/AddMyRestaurantFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/restaurant_detail/RestaurantDetailFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/restaurant_search/RestaurantSearchFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/BottomSheetManager.kt
  Aos/app/src/main/res/drawable/rect_primary1_nostroke_top_radius20.xml
  Aos/app/src/main/res/drawable/rect_primary3_nostroke_30radius.xml
  Aos/app/src/main/res/drawable/rect_primary3fill_nostroke_radius10.xml
  Aos/app/src/main/res/drawable/rect_primary6_nostroke_30radius.xml
  Aos/app/src/main/res/layout/bottom_sheet_restaurant.xml
  Aos/app/src/main/res/layout/fragment_add_my_restaurant.xml
  Aos/app/src/main/res/layout/fragment_home.xml
  Aos/app/src/main/res/layout/fragment_restaurant_detail.xml
  Aos/app/src/main/res/layout/fragment_restaurant_search.xml
  Aos/app/src/main/res/layout/item_home_filter.xml
  Aos/app/src/main/res/layout/item_home_search.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
Labels: feat, AOS

#96 [Home/be] 서울시 공공 api로 음식점 리스트 DB에 저장
  be/package-lock.json
  be/package.json
  be/src/restaurant/entities/restaurant.entity.ts
  be/src/restaurant/restaurant.controller.ts
  be/src/restaurant/restaurant.repository.ts
  be/src/restaurant/restaurant.service.ts
Labels: feat, BE

#97 [Pair/aos] data layer 처리 로직 변경
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/ApiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/BaseState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/BaseResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyDefaultInfoResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyInfoResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/IntroApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/MyPageApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RefreshApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/ValidationApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/ValidationRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/ValidationRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository_impl/MyPageRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMypageEditInfoMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/WishRestaurantListFragment.kt
  Aos/app/src/main/res/layout/fragment_edit_profile.xml
  Aos/app/src/main/res/layout/fragment_my_restaurant_list.xml
  Aos/app/src/main/res/layout/fragment_wish_restaurant_list.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
Labels: feat, AOS

#98 [Home/be] 서울시 음식점 api로 데이터 받아와 DB에 저장
  be/src/app.module.ts
  be/src/auth/auth.module.ts
  be/src/auth/auth.service.ts
  be/src/auth/dto/refreshToken.dto.ts
  be/src/custom.logger.ts
  be/src/logger.interceptor.ts
  be/src/restaurant/dto/restaurantInfo.dto.ts
  be/src/restaurant/dto/seachInfo.dto.ts
  be/src/restaurant/entities/restaurant.entity.ts
  be/src/restaurant/restaurant.controller.spec.ts
  be/src/restaurant/restaurant.controller.ts
  be/src/restaurant/restaurant.module.ts
  be/src/restaurant/restaurant.repository.ts
  be/src/restaurant/restaurant.service.spec.ts
  be/src/restaurant/restaurant.service.ts
  be/src/review/dto/reviewInfo.dto.ts
  be/src/review/entities/review.entity.ts
  be/src/review/review.module.ts
  be/src/user/entities/user.followList.entity.ts
  be/src/user/entities/user.restaurantlist.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.module.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.spec.ts
  be/src/user/user.service.ts
  be/src/utils/encryption.utils.ts
Labels: feat, BE

#99 [Home/be] 음식점 검색 시 현위치 기반 거리 순 정렬 조회
  be/src/restaurant/dto/seachInfo.dto.ts
  be/src/restaurant/restaurant.controller.ts
  be/src/restaurant/restaurant.repository.ts
Labels: feat, BE

#102 [Home/be] 엔티티 참조 관계 수정
  be/src/restaurant/entities/restaurant.entity.ts
  be/src/review/entities/review.entity.ts
  be/src/user/entities/user.entity.ts
  be/src/user/entities/user.followList.entity.ts
  be/src/user/entities/user.restaurantlist.entity.ts
Labels: refactor, BE

#103 [Home/be] 홈 화면 내 맛집 필터 + 위치기반 거리 적용
  be/src/restaurant/dto/seachInfo.dto.ts
  be/src/restaurant/restaurant.service.ts
  be/src/user/user.controller.ts
  be/src/user/user.followList.repository.ts
  be/src/user/user.module.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#106 [Home/be] 필터링된 맛집 리스트 응답 구현
  be/src/restaurant/dto/filterInfo.dto.ts
  be/src/restaurant/restaurant.controller.ts
  be/src/restaurant/restaurant.module.ts
  be/src/restaurant/restaurant.repository.ts
  be/src/restaurant/restaurant.service.ts
  be/src/user/user.module.ts
  be/src/user/user.restaurantList.repository.ts
Labels: feat, BE

#107 [Home/aos] 지도화면 음식점 필터링
  Aos/app/src/main/java/com/avengers/nibobnebob/app/NetworkManager.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/BindingAdapters.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeBindingAdapters.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/adapter/HomeFilterAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/model/UiFilterData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/model/UiMarkerData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/BottomSheetManager.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/DefaultDiffUtil.kt
  Aos/app/src/main/res/drawable/ic_logo_home.xml
  Aos/app/src/main/res/drawable/rect_primary3fill_nostroke_30radius.xml
  Aos/app/src/main/res/drawable/rect_primary6fill_nostroke_30radius.xml
  Aos/app/src/main/res/layout/bottom_sheet_restaurant.xml
  Aos/app/src/main/res/layout/fragment_home.xml
  Aos/app/src/main/res/layout/item_home_filter.xml
Labels: feat, AOS

#110 [Global/aos] Bearer Interceptor 구현
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/AccessTokenInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/RefreshTokenRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RefreshApi.kt
Labels: feat, AOS

#112 [MyPage/aos] 회원탈퇴, 로그아웃 구현
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/MyPageApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileViewModel.kt
  Aos/app/src/main/res/layout/fragment_my_page.xml
Labels: feat, AOS

#116 [Home/aos] 홈 음식점 검색
  Aos/.idea/deploymentTargetDropDown.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ApiModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/SearchRestaurantResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/HomeApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/adapter/RestaurantSearchAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/mapper/UiSearchResultDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/model/UiRestaurantData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/HideKeyBoard.kt
  Aos/app/src/main/res/drawable/rect_dark7fill_nostroke_10radius.xml
  Aos/app/src/main/res/layout/fragment_restaurant_search.xml
Labels: feat, AOS

#117 [MyPage/aos] 로그아웃, 회원 탈퇴 후 화면 전환
  Aos/app/src/main/java/com/avengers/nibobnebob/app/App.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/AccessTokenInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
Labels: feat, AOS

#118 [맛집상세보기/aos] 맛집 상세화면 구현
  Aos/.gitignore
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ApiModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/Location.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/RestaurantDetailResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/GlobalApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/GlobalRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/GlobalRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/mapper/UiRestaurantInfoDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/model/UiRestaurantDetailData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/model/UiReviewData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/restaurant_detail/RestaurantDetailFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/restaurantdetail/RestaurantDetailBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/restaurantdetail/RestaurantDetailFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/restaurantdetail/RestaurantDetailViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/restaurantdetail/adapter/RestaurantReviewAdapter.kt
  Aos/app/src/main/res/drawable/ic_thumbs_down_blank.xml
  Aos/app/src/main/res/drawable/ic_thumbs_down_fill.xml
  Aos/app/src/main/res/drawable/ic_thumbs_up_blank.xml
  Aos/app/src/main/res/drawable/ic_thumbs_up_fill.xml
  Aos/app/src/main/res/drawable/oval_primary1fill_nostroke.xml
  Aos/app/src/main/res/drawable/oval_primary2fill_nostroke.xml
  Aos/app/src/main/res/drawable/oval_primary3fill_nostroke.xml
  Aos/app/src/main/res/drawable/oval_primary4fill_nostroke.xml
  Aos/app/src/main/res/drawable/oval_primary5fill_nostroke.xml
  Aos/app/src/main/res/layout/fragment_restaurant_detail.xml
  Aos/app/src/main/res/layout/item_review_list.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
  Aos/app/src/main/res/values/strings.xml
Labels: feat, AOS

#123 [Global/aos] 전역 Refactoring
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/IntroApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/ValidationApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/customview/CalendarDatePicker.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/customview/RestaurantBottomSheet.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/DataExtensions.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/UiExtensions.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/BottomSheetManager.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/DatePicker.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/HideKeyBoard.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/ValidationUtil.kt
  Aos/app/src/main/res/values/themes.xml
Labels: feat, refactor, AOS

#127 [Follow/be] 팔로우/팔로잉 리스트, 팔로우/언팔로우, 유저 자동완성 검색, 다른 유저 메인페이지 정보
  be/src/user/user.controller.ts
  be/src/user/user.followList.repository.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#111 [맛집등록하기/be] 맛집 등록 api 응답 구현
  be/src/review/dto/reviewInfo.dto.ts
  be/src/review/review.module.ts
  be/src/review/review.repository.ts
  be/src/user/user.controller.ts
  be/src/user/user.module.ts
  be/src/user/user.service.ts
Labels: feat, BE

#128 마이페이지 로그아웃
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#129 맛집 등록하기
  be/src/review/dto/reviewInfo.dto.ts
  be/src/review/review.module.ts
  be/src/review/review.repository.ts
  be/src/user/user.controller.ts
  be/src/user/user.module.ts
  be/src/user/user.service.ts
Labels: BE

#130 팔로우 탭 기능 구현
  be/src/user/user.controller.ts
  be/src/user/user.followList.repository.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#131 [맛집리스트 등록/be] 등록, 삭제, 재등록
  be/src/review/dto/reviewInfo.dto.ts
  be/src/review/entities/review.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: feat, fix, refactor, BE

#132 맛집 리스트 재등록, 삭제
  be/src/review/dto/reviewInfo.dto.ts
  be/src/review/entities/review.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: BE

#135 [팔로우/be] 다른 사용자 추천, 팔로우/팔로잉 응답 수정
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: feat, refactor, BE

#136 다른 사용자 추천, 팔로우/팔로잉 응답 수정
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#138 [Follow/be] 팔로우/팔로워/추천 사용자 리스트 응답 구조 수정
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: refactor, BE

#139 팔로우/팔로워/추천 사용자 리스트 응답 구조 수정
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#137 [Home/be] 홈에서 발생하는 에러 fix 및 응답 형태 변경
  be/src/restaurant/dto/filterInfo.dto.ts
  be/src/restaurant/dto/location.dto.ts
  be/src/restaurant/dto/seachInfo.dto.ts
  be/src/restaurant/restaurant.controller.ts
  be/src/restaurant/restaurant.repository.ts
  be/src/restaurant/restaurant.service.ts
  be/src/user/user.controller.ts
Labels: feat, fix, BE

#140 홈 화면 에러 수정 및 응답 구조 변경
  be/src/restaurant/dto/filterInfo.dto.ts
  be/src/restaurant/dto/location.dto.ts
  be/src/restaurant/dto/seachInfo.dto.ts
  be/src/restaurant/restaurant.controller.ts
  be/src/restaurant/restaurant.repository.ts
  be/src/restaurant/restaurant.service.ts
  be/src/user/user.controller.ts
Labels: BE

#133 [맛집등록하기/aos] API 연결
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/AddRestaurantRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/GlobalApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/GlobalRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/GlobalRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/restaurantadd/AddMyRestaurantViewModel.kt
  Aos/app/src/main/res/layout/dialog_one_button_title.xml
  Aos/app/src/main/res/layout/dialog_two_button_title.xml
Labels: feat, AOS

#141 [MyPage/aos] 로그아웃 api 연결 및 연령대 표시
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/DataExtensions.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyPageInfoDataMapper.kt
Labels: feat, AOS

#142 [Following] 팔로우/팔로잉/유저추천
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ApiModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/FollowListResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/FollowApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/FollowRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/FollowRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/FollowBindingAdapters.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/FollowFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/FollowViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/adapter/FollowAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/detail/FollowDetailFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/mapper/UiFollowDatamapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/model/UiFollowData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/search/FollowSearchFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/adapter/RestaurantSearchAdapter.kt
  Aos/app/src/main/res/drawable/ic_test.png
  Aos/app/src/main/res/drawable/rect_dark6fill_nostroke_20radius.xml
  Aos/app/src/main/res/drawable/rect_primary4fill_nostroke_20radius.xml
  Aos/app/src/main/res/drawable/rect_primarylight3fill_nostroke_10radius.xml
  Aos/app/src/main/res/layout/fragment_follow.xml
  Aos/app/src/main/res/layout/fragment_follow_detail.xml
  Aos/app/src/main/res/layout/fragment_follow_search.xml
  Aos/app/src/main/res/layout/item_follower.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
  Aos/app/src/main/res/values/themes.xml
Labels: feat, AOS

#134 [Home/aos] 홈 화면 API 연동, 현재위치 갱신
  Aos/app/src/main/java/com/avengers/nibobnebob/config/AccessTokenInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/FilterRestaurantResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/FollowingResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/Location.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/SearchRestaurantResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/HomeApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/customview/RestaurantBottomSheet.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/mapper/UiFilterRestaurantDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/mapper/UiSearchResultDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/model/UiMarkerData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/model/UiRestaurantData.kt
  Aos/app/src/main/res/layout/bottom_sheet_restaurant.xml
Labels: feat, AOS

#144 [Home/be] 음식점 정보 응답 시 리뷰를 반영하여 응답
  be/src/restaurant/restaurant.controller.ts
  be/src/restaurant/restaurant.module.ts
  be/src/restaurant/restaurant.repository.ts
  be/src/restaurant/restaurant.service.ts
Labels: feat, refactor, BE

#151 전역 리팩토링
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/ic_app_logo-playstore.png
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ApiModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/FollowFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/FollowViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/mapper/UiRestaurantInfoDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/model/UiRestaurantDetailData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/model/UiReviewData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantadd/AddMyRestaurantBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantadd/AddMyRestaurantFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantadd/AddMyRestaurantViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/adapter/RestaurantReviewAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
  Aos/app/src/main/res/drawable/ic_app_logo.xml
  Aos/app/src/main/res/drawable/ic_app_logo_foreground.xml
  Aos/app/src/main/res/drawable/ic_marker.xml
  Aos/app/src/main/res/layout/activity_splash.xml
  Aos/app/src/main/res/layout/fragment_add_my_restaurant.xml
  Aos/app/src/main/res/layout/fragment_restaurant_detail.xml
  Aos/app/src/main/res/layout/item_review_list.xml
  Aos/app/src/main/res/mipmap-anydpi-v26/ic_app_logo.xml
  Aos/app/src/main/res/mipmap-anydpi-v26/ic_app_logo_round.xml
  Aos/app/src/main/res/mipmap-hdpi/ic_app_logo.webp
  Aos/app/src/main/res/mipmap-hdpi/ic_app_logo_round.webp
  Aos/app/src/main/res/mipmap-mdpi/ic_app_logo.webp
  Aos/app/src/main/res/mipmap-mdpi/ic_app_logo_round.webp
  Aos/app/src/main/res/mipmap-xhdpi/ic_app_logo.webp
  Aos/app/src/main/res/mipmap-xhdpi/ic_app_logo_round.webp
  Aos/app/src/main/res/mipmap-xxhdpi/ic_app_logo.webp
  Aos/app/src/main/res/mipmap-xxhdpi/ic_app_logo_round.webp
  Aos/app/src/main/res/mipmap-xxxhdpi/ic_app_logo.webp
  Aos/app/src/main/res/mipmap-xxxhdpi/ic_app_logo_round.webp
  Aos/app/src/main/res/navigation/nav_graph.xml
  Aos/app/src/main/res/values/ic_app_logo_background.xml
  Aos/app/src/main/res/values/strings.xml
Labels: feat, refactor, AOS

#152 [WishList/be] 위시리스트 등록/삭제/가져오기 구현
  be/src/restaurant/restaurant.repository.ts
  be/src/user/entities/user.wishrestaurantlist.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.module.ts
  be/src/user/user.service.ts
  be/src/user/user.wishrestaurantList.repository.ts
Labels: feat, BE

#150 [Follow/be] 다른 유저 메인 페이지 정보 요청 api 응답 구조 수정
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: refactor, BE

#153 다른 유저 메인 페이지 정보 요청 api 응답 속성 추가
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: BE

#154 [Home/be] 위시 맛집리스트 등록 여부 응답 및 내 맛집 리스트 응답 수정
  be/src/restaurant/restaurant.repository.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#155 [Global/be] prettier 적용 및 api tag 적용
  be/src/auth/auth.controller.ts
  be/src/main.ts
  be/src/restaurant/dto/filterInfo.dto.ts
  be/src/restaurant/dto/location.dto.ts
  be/src/restaurant/dto/seachInfo.dto.ts
  be/src/restaurant/entities/restaurant.entity.ts
  be/src/restaurant/restaurant.controller.ts
  be/src/restaurant/restaurant.repository.ts
  be/src/restaurant/restaurant.service.ts
  be/src/review/entities/review.entity.ts
  be/src/review/review.module.ts
  be/src/review/review.repository.ts
  be/src/user/entities/user.entity.ts
  be/src/user/entities/user.restaurantlist.entity.ts
  be/src/user/entities/user.wishrestaurantlist.entity.ts
  be/src/user/user.controller.ts
  be/src/user/user.followList.repository.ts
  be/src/user/user.module.ts
  be/src/user/user.repository.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
  be/src/user/user.wishrestaurantList.repository.ts
Labels: feat, BE

#158 다른 유저 메인 마이페이지 에러 및 응답 수정
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: BE

#161 [Global/be] api 응답 fix, 유저 검색 필터 중첩 적용
  be/src/restaurant/restaurant.repository.ts
  be/src/user/user.controller.ts
  be/src/user/user.service.ts
  be/src/utils/parsearraypipe.ts
Labels: feat, fix, BE

#162 api 응답 수정
  be/src/restaurant/restaurant.repository.ts
  be/src/user/user.controller.ts
  be/src/user/user.service.ts
  be/src/utils/parsearraypipe.ts
Labels: BE

#163 Review 등록 Validation, 응답 구조 변경, 유저 자동 검색 응답 변경
  be/src/restaurant/restaurant.service.ts
  be/src/review/dto/reviewInfo.dto.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#167 마이페이지 테스트 코드 작성
  be/docker-compose.yml
  be/package.json
  be/src/restaurant/restaurant.service.ts
  be/src/user/entities/user.restaurantlist.entity.ts
  be/src/user/entities/user.wishrestaurantlist.entity.ts
  be/src/user/user.service.spec.ts
Labels: BE

#164 [Home/aos] 검색 기능 마무리
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/NavigationExtensions.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapFragment.kt
  Aos/app/src/main/res/layout/fragment_home.xml
  Aos/app/src/main/res/layout/fragment_restaurant_search.xml
  Aos/app/src/main/res/layout/fragment_restaurant_search_map.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
Labels: feat, AOS

#168 [MyPage/aos] 위시 맛집 리스트 구현
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyListDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyWishListDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyListData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyWishData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantListViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/MyWishAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/MyWishListViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/WishRestaurantListFragment.kt
  Aos/app/src/main/res/layout/fragment_wish_restaurant_list.xml
  Aos/app/src/main/res/layout/item_my_list.xml
  Aos/app/src/main/res/layout/item_wish_list.xml
  Aos/app/src/main/res/menu/my_page_wish_list_menu.xml
  Aos/app/src/main/res/values/strings.xml
Labels: feat, AOS

#165 [맛집상세보기/aos] 맛집 상세보기 API연결 및 추가 작업
  Aos/.idea/deploymentTargetDropDown.xml
  Aos/.idea/misc.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/RestaurantDetailResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/NavigationExtensions.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/mapper/UiRestaurantDetailDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/mapper/UiRestaurantInfoDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/mapper/UiRestaurantReviewDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/model/UiRestaurantDetailData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/model/UiReviewData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyListDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyWishListDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyListData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyWishData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantListViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/MyWishAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/MyWishListViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/WishRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/TimeUtil.kt
  Aos/app/src/main/res/layout/fragment_home.xml
  Aos/app/src/main/res/layout/fragment_restaurant_detail.xml
  Aos/app/src/main/res/layout/fragment_restaurant_search.xml
  Aos/app/src/main/res/layout/fragment_restaurant_search_map.xml
  Aos/app/src/main/res/layout/fragment_wish_restaurant_list.xml
  Aos/app/src/main/res/layout/item_my_list.xml
  Aos/app/src/main/res/layout/item_review_list.xml
  Aos/app/src/main/res/layout/item_wish_list.xml
  Aos/app/src/main/res/menu/my_page_wish_list_menu.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
  Aos/app/src/main/res/values/strings.xml
Labels: feat, AOS

#175 [Mypage - Final/be] 마이페이지 프로필 사진을 object storage를 사용하여 저장
  be/.gitignore
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/auth/auth.service.spec.ts
  be/src/aws/aws.module.ts
  be/src/aws/aws.service.spec.ts
  be/src/aws/aws.service.ts
  be/src/user/dto/userInfo.dto.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.repository.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#176 유저 프로필 사진을 object storage에 저장 및 응답
  be/.gitignore
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/auth/auth.service.spec.ts
  be/src/aws/aws.module.ts
  be/src/aws/aws.service.spec.ts
  be/src/aws/aws.service.ts
  be/src/user/dto/userInfo.dto.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.repository.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: BE

#174 [home/aos] 필터 클릭시 이동 알고리즘 적용
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
Labels: feat, AOS

#179 [Pair/aos]bottom sheet 작업 및 MVP 기능 마무리
  Aos/.idea/misc.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/app/NetworkManager.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/RestaurantResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/WishRestaurantResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/HomeApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/MyPageApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/customview/RestaurantBottomSheet.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/BindingAdapters.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/mapper/UiRestaurantDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyListDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyWishListDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/WishRestaurantListFragment.kt
  Aos/app/src/main/res/layout/bottom_sheet_restaurant.xml
  Aos/app/src/main/res/layout/fragment_restaurant_detail.xml
Labels: feat, refactor, AOS
