Repository boostcampwm2023/and06-nibobnebob, pull requests merged in 2023-12, with the labels that each got.

#186 [Global/aos] BindingAdapter 및 전반적인 디자인 수정
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/ButtonBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/ImageViewBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/RecyclerViewBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/TextInputBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/TextViewBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/FollowBindingAdapters.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/search/FollowBindingAdapater.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantadd/AddMyRestaurantBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeBindingAdapters.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileViewModel.kt
  Aos/app/src/main/res/drawable/rect_primary2fill_nostroke_28radius.xml
  Aos/app/src/main/res/layout/bottom_sheet_restaurant.xml
  Aos/app/src/main/res/layout/dialog_one_button_title.xml
  Aos/app/src/main/res/layout/dialog_select_region.xml
  Aos/app/src/main/res/layout/dialog_two_button_title.xml
  Aos/app/src/main/res/layout/fragment_add_my_restaurant.xml
  Aos/app/src/main/res/layout/fragment_detail_signup.xml
  Aos/app/src/main/res/layout/fragment_edit_profile.xml
  Aos/app/src/main/res/layout/fragment_follow.xml
  Aos/app/src/main/res/layout/fragment_follow_search.xml
  Aos/app/src/main/res/layout/fragment_home.xml
  Aos/app/src/main/res/layout/fragment_login.xml
  Aos/app/src/main/res/layout/fragment_my_page.xml
  Aos/app/src/main/res/layout/fragment_restaurant_detail.xml
  Aos/app/src/main/res/layout/fragment_restaurant_search.xml
  Aos/app/src/main/res/layout/fragment_user_detail.xml
  Aos/app/src/main/res/layout/item_home_filter.xml
  Aos/app/src/main/res/layout/item_review_list.xml
  Aos/app/src/main/res/values/strings.xml
Labels: fix, refactor, AOS

#188 feat : docker를 이용한 자동 배포 설정 #35
  .github/workflows/be-autodeploy.yml
  be/Dockerfile
  be/dockerignore
Labels: feat, BE

#190 위시 맛집 포함 여부 요청 api 구현
  be/src/user/user.controller.ts
  be/src/user/user.service.ts
Labels: BE

#192 일반 로그인 구현
  be/src/auth/auth.controller.ts
  be/src/auth/auth.module.ts
  be/src/auth/auth.repository.ts
  be/src/auth/auth.service.ts
  be/src/auth/dto/loginInfo.dto.ts
  be/src/auth/entity/auth.refreshtoken.entity.ts
  be/src/user/user.service.ts
Labels: BE

#191 [Global/aos] init 템플릿 메소드 패턴 적옹 및 네트워크 간단한 대응
  Aos/app/src/main/java/com/avengers/nibobnebob/app/NetworkManager.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/FollowFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/search/FollowSearchFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/search/FollowSearchViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantadd/AddMyRestaurantFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/userdetail/UserDetailFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/WishRestaurantListFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
Labels: feat, refactor, AOS

#196 object storage를 활용한 사진 저장 및 응답 구현(multipart)
  be/package-lock.json
  be/package.json
  be/src/auth/auth.controller.ts
  be/src/main.ts
  be/src/restaurant/restaurant.service.ts
  be/src/review/dto/reviewInfo.dto.ts
  be/src/review/entities/review.entity.ts
  be/src/user/dto/userInfo.dto.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#194 [Login-Final/aos] 일반로그인 / 회원가입 구현
  Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/BasicLoginRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/LoginResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/IntroApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RefreshApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/model/UiLoginData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/BasicSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/BasicSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/SignupUiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/ValidationUtil.kt
  Aos/app/src/main/res/layout/fragment_basic_signup.xml
  Aos/app/src/main/res/layout/fragment_login.xml
  Aos/app/src/main/res/navigation/intro_nav_graph.xml
Labels: feat, AOS

#197 [Signup-Final/aos] 회원가입 프로필 사진 적용 (API 연결 전)
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/BasicLoginRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/DetailSignupRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/LoginResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/IntroApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RefreshApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/DataExtensions.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/ImageViewBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/model/UiLoginData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/BasicSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/BasicSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/SignupUiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/ValidationUtil.kt
  Aos/app/src/main/res/layout/fragment_basic_signup.xml
  Aos/app/src/main/res/layout/fragment_detail_signup.xml
  Aos/app/src/main/res/layout/fragment_login.xml
  Aos/app/src/main/res/navigation/intro_nav_graph.xml
Labels: feat, AOS

#202 [mypage/aos] 마이페이지 Ui, 프로필 수정 로직 변경
  Aos/app/src/main/AndroidManifest.xml
  Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/BasicLoginRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/DetailSignupRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/EditMyInfoRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/LoginResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyDefaultInfoResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyInfoResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/HomeApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/IntroApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RefreshApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/DataExtensions.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/NavigationExtensions.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/ButtonBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/ImageButtonBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/ImageViewBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/model/UiLoginData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/BasicSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/BasicSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/SignupUiState.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantadd/AddMyRestaurantFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/mapper/UiRestaurantDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyPageInfoDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMypageEditInfoMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyPageEditInfoData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyPageMainInfoData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/ValidationUtil.kt
  Aos/app/src/main/res/layout/fragment_basic_signup.xml
  Aos/app/src/main/res/layout/fragment_detail_signup.xml
  Aos/app/src/main/res/layout/fragment_edit_profile.xml
  Aos/app/src/main/res/layout/fragment_home.xml
  Aos/app/src/main/res/layout/fragment_login.xml
  Aos/app/src/main/res/layout/fragment_my_page.xml
  Aos/app/src/main/res/navigation/intro_nav_graph.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
Labels: feat, AOS

#199 [Home/aos] 검색 후 지도에서 위시리스트 여부 업데이트
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/RestaurantIsWishResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
Labels: feat, fix, AOS

#207 [맛집, 위시 맛집 리스트/be] 내 맛집, 위시 맛집 리스트 응답 시 정렬 및 페이징 기능 구현
  be/src/user/user.controller.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
  be/src/user/user.wishrestaurantList.repository.ts
  be/src/utils/sortInfo.dto.ts
Labels: feat, BE

#211 맛집, 위시 맛집 정렬 및 페이징 기능 구현
  be/src/user/user.controller.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
  be/src/user/user.wishrestaurantList.repository.ts
  be/src/utils/sortInfo.dto.ts
Labels: BE

#212 리뷰 평가 및 정렬, 페이징 기능 구현
  be/src/restaurant/restaurant.service.ts
  be/src/review/entities/review.entity.ts
  be/src/review/entities/review.like.entity.ts
  be/src/review/review.controller.spec.ts
  be/src/review/review.controller.ts
  be/src/review/review.like.repository.ts
  be/src/review/review.module.ts
  be/src/review/review.repository.ts
  be/src/review/review.service.spec.ts
  be/src/review/review.service.ts
  be/src/user/user.service.ts
Labels: BE

#213 [Global/aos] intro, mypage, refresh domain layer 구현
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/LoginResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyDefaultInfoResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyInfoResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/IntroApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/MyPageApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RefreshApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/model/LoginData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/model/MyDefaultInfoData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/model/MyInfoData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/repository/IntroRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/repository/MyPageRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyPageInfoDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMypageEditInfoMapper.kt
Labels: feat, refactor, AOS

#210 [Home-Final/be] 음식 추천 기능 api 구현
  be/src/user/user.controller.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#220 음식점 추천 기능 구현
  be/src/user/user.controller.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: BE

#217 [Follow-Final/be] 추천 유저 알고리즘 구현
  be/src/review/dto/reviewInfo.dto.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#222 FINAL 팔로우 추천 유저 기능 구현
  be/src/review/dto/reviewInfo.dto.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: BE

#221 [Home-Final/be] 음식점 관련 응답에 사진 추가
  be/src/restaurant/restaurant.controller.ts
  be/src/restaurant/restaurant.repository.ts
  be/src/restaurant/restaurant.service.ts
  be/src/review/dto/reviewInfo.dto.ts
  be/src/review/entities/review.entity.ts
  be/src/review/review.repository.ts
  be/src/review/review.service.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.service.ts
Labels: feat, BE

#223 음식점 사진 응답 추가
  be/src/restaurant/restaurant.controller.ts
  be/src/restaurant/restaurant.repository.ts
  be/src/restaurant/restaurant.service.ts
  be/src/review/entities/review.entity.ts
  be/src/review/review.repository.ts
  be/src/review/review.service.ts
  be/src/user/entities/user.entity.ts
  be/src/user/user.service.ts
Labels: BE

#224 [Global-Final/be] 회원가입 시 홈화면 진입을 위한 토큰값 반환
  be/src/auth/auth.service.ts
  be/src/user/user.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: feat, BE

#228 [mypage/aos] 마이페이지 수정 사진 구현
  Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/EditMyInfoRequest.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/MyPageApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/repository/MyPageRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/customview/ImageDialog.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/ButtonBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/ImageViewBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainActivity.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileViewModel.kt
  Aos/app/src/main/res/layout/dialog_image_view.xml
  Aos/app/src/main/res/layout/fragment_edit_profile.xml
  Aos/app/src/main/res/layout/fragment_my_page.xml
Labels: feat, AOS

#232 [Home/aos] 홈화면 필터, 주변 맛집 마커 보완
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
  Aos/app/src/main/res/layout/fragment_home.xml
Labels: refactor, AOS

#235 [Global-Final/be] 음식점 추천 에러 fix, 음식점 상세 응답에 데이터 추가
  be/src/restaurant/restaurant.service.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: feat, fix, BE

#236 맛집 상세 페이지 리뷰 응답 데이터 추가, 음식 추천 에러 fix
  be/src/restaurant/restaurant.service.ts
  be/src/user/user.restaurantList.repository.ts
  be/src/user/user.service.ts
Labels: BE

#240 [Global-Final/be] Cron 스케줄러 적용
  be/package-lock.json
  be/package.json
  be/src/restaurant/restaurant.module.ts
  be/src/restaurant/restaurant.service.ts
Labels: feat, BE

#241 cron을 적용하여 DB 업데이트
  be/package-lock.json
  be/package.json
  be/src/restaurant/restaurant.module.ts
  be/src/restaurant/restaurant.service.ts
Labels: BE

#245 [Global/be] 팔로우 / 팔로워 리스트 응답 사진, 리뷰 이미지 응답 수정
  be/src/restaurant/restaurant.service.ts
  be/src/review/review.service.ts
  be/src/user/user.service.ts
Labels: feat, BE

#243 [Login,Logout/aos]자동로그인 관리
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
  Aos/app/src/main/res/layout/fragment_login.xml
Labels: feat, fix, AOS

#244 [리뷰 전체보기/aos] 리뷰 정렬 및 페이징, 리뷰평가
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/RestaurantDetailResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/model/RestaurantDetailData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/repository/RestaurantRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/usecase/restaurant/GetSortedReviewUseCase.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/mapper/UiRestaurantReviewDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/model/UiReviewData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantadd/AddMyRestaurantViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantreview/RestaurantReviewsFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantreview/RestaurantReviewsViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/mapper/UiSearchResultDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileViewModel.kt
  Aos/app/src/main/res/color/selector_next_btn_text.xml
  Aos/app/src/main/res/drawable/rect_primarylight3fill_nostroke_8radius.xml
  Aos/app/src/main/res/layout/fragment_restaurant_detail.xml
  Aos/app/src/main/res/layout/fragment_restaurant_reviews.xml
  Aos/app/src/main/res/layout/item_home_filter.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
  Aos/app/src/main/res/values/strings.xml
Labels: feat, AOS

#256 [Global-Final/be] Object Storage 저장 이미지 리사이징
  be/package-lock.json
  be/package.json
  be/src/aws/aws.service.ts
  be/src/main.ts
Labels: feat, BE

#257 Object Storage 저장 이미지 리사이징
  be/package-lock.json
  be/package.json
  be/src/aws/aws.service.ts
  be/src/main.ts
Labels: BE

#261 [hotfix/aos] Hotfix
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/repository/RestaurantRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/TextViewBindingAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/BasicSignupViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/mapper/UiUserDetailDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/model/UiUserDetailData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/userdetail/UserDetailFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/userdetail/UserDetailViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/userdetail/adapter/UserDetailRestaurantAdapter.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/WishRestaurantListFragment.kt
  Aos/app/src/main/res/layout/bottom_sheet_restaurant.xml
  Aos/app/src/main/res/layout/fragment_add_my_restaurant.xml
  Aos/app/src/main/res/layout/fragment_basic_signup.xml
  Aos/app/src/main/res/layout/fragment_follow.xml
  Aos/app/src/main/res/layout/fragment_login.xml
  Aos/app/src/main/res/navigation/nav_graph.xml
  Aos/app/src/main/res/values/strings.xml
Labels: fix, refactor, AOS

#262 [Hotfix/aos]Hotfix
  Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyRestaurantResponse.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/model/MyRestaurantData.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/repository/RestaurantRepository.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/domain/usecase/restaurant/GetMyRestaurantListUseCase.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyListDataMapper.kt
  Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyListData.kt
  Aos/app/src/main/res/layout/fragment_basic_signup.xml
  Aos/app/src/main/res/layout/fragment_home.xml
  Aos/app/src/main/res/layout/fragment_login.xml
  Aos/app/src/main/res/layout/fragment_restaurant_search.xml
  Aos/app/src/main/res/layout/fragment_restaurant_search_map.xml
Labels: fix, AOS
